keystore:
  config:
    uri: classpath:keystore-dev.jks
    type: pkcs12
    password: nunofernandes
    certificate:
      alias: nunofernandes
signature:
  metadata:
    name: Nuno Fernandes
    location: Braga
    reason: Assinar documento
    appName: Signer Service
import:
  directory: /home/nunomsf/projects/nunofern/share/import
export:
  directory:
    success: /home/nunomsf/projects/nunofern/share/export
    fail: /home/nunomsf/projects/nunofern/share/fail
application:
  config:
    signablefileConfig:
      PDF:
        try-fix-corrupted-files: false
        try-fix-corrupted-files-temp-path: "/home/nunomsf/projects/nunofern/share/import/~temp"

